version: "3.9"

services:
  postgresql:
    extends:
      file: ./services.base.yaml
      service: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: bytezza_auth_service_test
